name: Continuous Delivery

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/vollmed-api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vollmed-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/vollmed-api:${{ github.sha }}'
        env:
          POSTGRES_DB_TEST_URL: ${{ secrets.POSTGRES_DB_TEST_URL }}
